### ISSUE TITLE
Enable conda environments for multiple users

### ISSUE THREAD

**Issue by davidskalinder** [davidskalinder/mpeds-coder#64]
#61 requires running Python scripts that use MAI's environment but are not run by MAI.  ATM the MAI (mpeds) env is only set up for the www user, requiring even more sudoing than usual.  Possible approach: add anaconda bins to the other user's path and follow [this approach](https://stackoverflow.com/questions/50627685/how-can-i-activate-another-users-conda-environment) to copy the env.

**Comment by davidskalinder** [comment]
Note though that [this issue](https://stackoverflow.com/questions/36117904/error-conda-can-only-be-installed-into-the-root-environment) (FSM save us from stackoverflow link rot) seems to crop up.  Hopefully removing the conda* dependencies from the env will sort it out...

**Comment by davidskalinder** [comment]
Ah, good old dependency hell:

```
UnsatisfiableError: The following specifications were found to be in conflict:
  - cairo 1.12.18 4 -> fontconfig 2.11.1 -> freetype 2.5*
  - pil 1.1.7 py27_1 -> freetype 2.4*
Use "conda info <package>" to see the dependencies for each package.
```

Python's package management is like handing [this guy](https://xkcd.com/353/) an anvil.

**Comment by davidskalinder** [comment]
Started by trying to track these down and remove unused dependencies following [this approach](https://stackoverflow.com/questions/26101972/how-to-identify-conda-package-dependents).  But I'm getting lots of these, for increasingly necessary-sounding things, so I might need to move to a [whitelist approach](https://stackoverflow.com/questions/58216917/create-conda-environment-found-conflicts-when-solving-environment-and-findi) rather than a blacklist approach...

**Comment by davidskalinder** [comment]
A handy side effect of this is that I've had to grep-and-regex together a requirements list from the import statements (though of course without any version info):

```
config
csv
datab
datetime
fl
glob
itertools
json
lxml
math
models
mpeds_coder
numpy
os
pand
pickle
pytz
random
re
smtplib
sqlalchemy
sqlalchemy.exc
sqlalchemy.ext.declarative
sqlalchemy.orm
sqlalchemy.schema
sqlalchemy.sql
sqlite3
string
sys
time
urllib
urllib.request
urllib2
yaml
```

... plus `Python 2.7.11 :: Anaconda 2.3.0`...

**Comment by davidskalinder** [comment]
So it _looks_ like the following yaml file is good enough for the data wrangling environment at least.  It's waay shorter than the one produced by `conda env export -n mpeds` (after removing all the lines without a match from the import list), and I haven't tested it by running full-blown MAI with it, but I think it should cover all the imported modules above with no conflicts.  The env can be created by saving the below in `mpeds_env.yml` and running `conda env create -f ~/mpeds_env.yml`.

```
name: mpeds
channels:
- defaults
dependencies:
- flask=0.10.1=py27_1
- lxml=3.4.4=py27_0
- numpy=1.9.2=py27_0
- pandas=0.16.2=np19py27_0
- pytz=2015.4=py27_0
- sqlalchemy=1.0.5=py27_0
- sqlite=3.9.2=0
- system=5.8=2
- yaml=0.1.6=0
- pip:
  - flask-login==0.2.11
```

**Comment by davidskalinder** [comment]
Well, never mind:

```
Traceback (most recent call last):
  File "test.py", line 9, in <module>
    convert_unicode=True)
  File "/home/username/.conda/envs/mpeds/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 386, in create_engine
    return strategy.create(*args, **kwargs)
  File "/home/username/.conda/envs/mpeds/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 75, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/home/username/.conda/envs/mpeds/lib/python2.7/site-packages/sqlalchemy/dialects/mysql/mysqldb.py", line 92, in dbapi
    return __import__('MySQLdb')
ImportError: No module named MySQLdb
```

Adding `  - mysql-python==1.2.5` to the `pip` section of the YAML file and running `conda env update --file ~/mpeds_env.yml --prune` fixes it this time; presumably lots more of those await in the future.  I won't log those here unless something unexpected happens.

**Comment by davidskalinder** [comment]
For reference, here's the full output of `conda env export -n mpeds`:

```
name: mpeds
channels:
- defaults
dependencies:
- _license=1.1=py27_0
- abstract-rendering=0.5.1=np19py27_0
- alabaster=0.7.3=py27_0
- anaconda=2.3.0=np19py27_0
- argcomplete=0.8.9=py27_0
- astropy=1.0.3=np19py27_0
- atom=0.3.9=py27_0
- babel=1.3=py27_0
- bcolz=0.9.0=np19py27_0
- beautiful-soup=4.3.2=py27_0
- binstar=0.11.0=py27_0
- bitarray=0.8.1=py27_0
- blaze=0.6.3=np19py27_0
- blaze-core=0.8.0=np19py27_0
- blz=0.6.2=np19py27_1
- bokeh=0.9.0=np19py27_0
- boto=2.38.0=py27_0
- bottleneck=1.0.0=np19py27_0
- cairo=1.12.18=4
- casuarius=1.1=py27_0
- cdecimal=2.3=py27_0
- certifi=14.05.14=py27_0
- cffi=1.1.0=py27_0
- chaco=4.4.1=np19py27_0
- clyent=0.3.4=py27_0
- colorama=0.3.3=py27_0
- configobj=5.0.6=py27_0
- cryptography=0.9.1=py27_0
- curl=7.43.0=0
- cython=0.22.1=py27_0
- cytoolz=0.7.3=py27_0
- datashape=0.4.5=np19py27_0
- dateutil=2.1=py27_2
- decorator=3.4.2=py27_0
- docutils=0.12=py27_0
- dynd-python=0.6.5=np19py27_0
- enable=4.3.0=np19py27_2
- enaml=0.9.8=py27_0
- enum34=1.0.4=py27_0
- fastcache=1.0.2=py27_0
- flask=0.10.1=py27_1
- fontconfig=2.11.1=4
- freetype=2.5.2=2
- funcsigs=0.4=py27_0
- future=0.13.1=py27_0
- futures=2.1.6=py27_0
- gevent=1.0.1=py27_0
- gevent-websocket=0.9.3=py27_0
- greenlet=0.4.7=py27_0
- grin=1.2.1=py27_1
- h5py=2.5.0=np19py27_3
- hdf5=1.8.15.1=1
- idna=2.0=py27_0
- ipaddress=1.0.7=py27_0
- ipython=3.2.0=py27_0
- ipython-notebook=3.2.0=py27_0
- ipython-qtconsole=3.2.0=py27_0
- itsdangerous=0.24=py27_0
- jdcal=1.0=py27_0
- jedi=0.8.1=py27_0
- jinja2=2.7.3=py27_1
- jpeg=8d=0
- jsonschema=2.4.0=py27_0
- kiwisolver=0.1.3=py27_0
- lcms=1.19=0
- libdynd=0.6.5=0
- libffi=3.0.13=0
- libpng=1.6.17=0
- libsodium=0.4.5=0
- libtiff=4.0.2=1
- libxml2=2.9.2=0
- libxslt=1.1.28=0
- llvm=3.3=0
- llvmlite=0.5.0=py27_0
- llvmpy=0.12.7=py27_0
- lxml=3.4.4=py27_0
- markupsafe=0.23=py27_0
- matplotlib=1.4.3=np19py27_2
- mistune=0.5.1=py27_1
- mock=1.0.1=py27_0
- mpi4py=1.3=py27_0
- mpich2=1.4.1p1=0
- multipledispatch=0.4.7=py27_0
- mysql=5.5.24=0
- networkx=1.9.1=py27_0
- nltk=3.0.3=np19py27_0
- nose=1.3.7=py27_0
- numba=0.19.1=np19py27_0
- numexpr=2.4.3=np19py27_0
- numpy=1.9.2=py27_0
- odo=0.3.2=np19py27_0
- openpyxl=1.8.5=py27_0
- openssl=1.0.2g=0
- pandas=0.16.2=np19py27_0
- patsy=0.3.0=np19py27_0
- pep8=1.6.2=py27_0
- pil=1.1.7=py27_1
- pillow=2.8.2=py27_0
- pip=8.1.0=py27_0
- pixman=0.26.2=0
- ply=3.6=py27_0
- psutil=2.2.1=py27_0
- ptyprocess=0.4=py27_0
- py=1.4.27=py27_0
- py2cairo=1.10.0=py27_2
- pyasn1=0.1.7=py27_0
- pycosat=0.6.1=py27_0
- pycparser=2.14=py27_0
- pycrypto=2.6.1=py27_0
- pycurl=7.19.5.1=py27_2
- pyface=4.4.0=py27_0
- pyflakes=0.9.2=py27_0
- pygments=2.0.2=py27_0
- pymysql=0.6.7=py27_0
- pyopenssl=0.15.1=py27_1
- pyparsing=2.0.3=py27_0
- pyqt=4.11.3=py27_1
- pytables=3.2.0=np19py27_0
- pytest=2.7.1=py27_0
- python=2.7.11=0
- python-dateutil=2.4.2=py27_0
- pytz=2015.4=py27_0
- pyyaml=3.11=py27_1
- pyzmq=14.7.0=py27_0
- qt=4.8.6=3
- readline=6.2=2
- redis=2.6.9=0
- redis-py=2.10.3=py27_0
- requests=2.9.1=py27_0
- rope=0.9.4=py27_1
- runipy=0.1.3=py27_0
- scikit-image=0.11.3=np19py27_0
- scikit-learn=0.16.1=np19py27_0
- scipy=0.15.1=np19py27_0
- setuptools=20.2.2=py27_0
- sip=4.16.5=py27_0
- six=1.9.0=py27_0
- snowballstemmer=1.2.0=py27_0
- sockjs-tornado=1.0.1=py27_0
- sphinx=1.3.1=py27_0
- sphinx_rtd_theme=0.1.7=py27_0
- spyder=2.3.5.2=py27_0
- spyder-app=2.3.5.2=py27_0
- sqlalchemy=1.0.5=py27_0
- sqlite=3.9.2=0
- ssl_match_hostname=3.4.0.2=py27_0
- statsmodels=0.6.1=np19py27_0
- sympy=0.7.6=py27_0
- system=5.8=2
- terminado=0.5=py27_0
- theano=0.7.0=np19py27_0
- tk=8.5.18=0
- toolz=0.7.2=py27_0
- tornado=4.2=py27_0
- traits=4.4.0=py27_0
- traitsui=4.4.0=py27_0
- ujson=1.33=py27_0
- unicodecsv=0.9.4=py27_0
- util-linux=2.21=0
- werkzeug=0.10.4=py27_0
- wheel=0.29.0=py27_0
- xlrd=0.9.3=py27_0
- xlsxwriter=0.7.3=py27_0
- xlwt=1.0.0=py27_0
- yaml=0.1.6=0
- zeromq=4.0.5=0
- zlib=1.2.8=0
- pip:
  - backports.ssl-match-hostname==3.4.0.2
  - beautifulsoup4==4.3.2
  - docker-compose==1.3.3
  - docker-py==1.3.1
  - dockerpty==0.3.4
  - docopt==0.6.2
  - flask-login==0.2.11
  - mysql-python==1.2.5
  - sphinx-rtd-theme==0.1.7
  - tables==3.2.0
  - texttable==0.8.3
  - websocket-client==0.32.0
prefix: /home/www/.conda/envs/mpeds
```
